### ISSUE TITLE
Editing case from rails_admin in production causes error intermittently

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#82] opened 2015-08-07 22:21 UTC
To replicate, change or add a title to a case. click to update, changes will not be made. updated show page will not be shown.

Everything works on local and staging.

Currently seems to be working on production. Leaving the issue, in case we see it again.

**Comment by trystant** [comment] 2015-10-06 08:58
@campgurus Considering that there hasn't been an issue with this recently, and I cannot reproduce, I am going to close this out. If you can reproduce and find that this is happening, please reopen with steps to reproduce. Thanks.

**Closed by trystant** 2015-10-06 08:58 UTC
