### ISSUE TITLE
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "articles" violates foreign key constraint "fk_rails_d221076f62" on table "links"
DETAIL:  Key (id)=(395) is still referenced from table "links".
: DELETE FROM "ar

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#171] opened 2015-09-04 14:52 UTC
View details in Rollbar: [https://rollbar.com/trystant/BOW/items/201/](https://rollbar.com/trystant/BOW/items/201/)

```

PG::ForeignKeyViolation: ERROR:  update or delete on table "articles" violates foreign key constraint "fk_rails_d221076f62" on table "links"
DETAIL:  Key (id)=(395) is still referenced from table "links".

  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb", line 606, in exec_prepared
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb", line 606, in block in exec_cache
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb", line 473, in block in log
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb", line 20, in instrument
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb", line 467, in log
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb", line 605, in exec_cache
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb", line 589, in execute_and_clear
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb", line 173, in exec_delete
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb", line 119, in delete
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb", line 14, in delete
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation.rb", line 477, in delete_all
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/persistence.rb", line 487, in destroy_row
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/counter_cache.rb", line 152, in destroy_row
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/locking/optimistic.rb", line 115, in destroy_row
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/persistence.rb", line 172, in destroy
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/callbacks.rb", line 292, in block in destroy
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 115, in call
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 115, in call
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 553, in block (2 levels) in compile
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 503, in call
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 503, in call
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 88, in run_callbacks
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/callbacks.rb", line 292, in destroy
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb", line 281, in block in destroy
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb", line 351, in block in with_transaction_returning_status
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb", line 213, in block in transaction
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb", line 184, in within_new_transaction
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb", line 213, in transaction
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb", line 220, in transaction
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb", line 348, in with_transaction_returning_status
  File "/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb", line 281, in destroy
  File "/app/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.6.7/lib/rails_admin/adapters/active_record.rb", line 47, in each
  File "/app/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.6.7/lib/rails_admin/adapters/active_record.rb", line 47, in destroy
  File "/app/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.6.7/lib/rails_admin/config/actions/bulk_delete.rb", line 26, in block (2 levels) in <class:BulkDelete>
  File "/app/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.6.7/app/controllers/rails_admin/main_controller.rb", line 22, in instance_eval
  File "/app/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.6.7/app/controllers/rails_admin/main_controller.rb", line 22, in bulk_delete
  File "/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb", line 4, in send_action
  File "/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb", line 198, in process_action
  File "/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb", line 10, in process_action
  File "/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb", line 20, in block in process_action
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 115, in call
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 115, in call
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 553, in block (2 levels) in compile
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 503, in call
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 503, in call
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb", line 88, in run_callbacks
  File "/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb", line 19, in process_action
  File "/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb", line 29, in process_action
  File "/app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb", line 32, in block in process_action
  File "/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb", line 164, in block in instrume

**Comment by campgurus** [comment] 2015-09-05 11:10
dupe of #9

**Closed** 2015-09-05 14:11 UTC
