### ISSUE TITLE
History Page content difficult to parse

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#71] opened 2015-07-31 18:07 UTC
The page is basically inscrutable at this point.  We need to parse the fields better so the user can see changes to the article easily.

**Comment by campgurus** [comment] 2015-08-20 18:51
This issue has essentially been resolved in development, but not yet merged to production.  tl;dr -- added a latest_update field to :articles and on save copy that field into @version meta data then shown in the history and mailer.

Specifically here is what has changed:
* Added a field for `latest_update" to the article model
* Added a fieldset to article/_form for inputting the latest_update text
* Edited articles_controller storng params to include :latest_update
* Added a `blurb' text field to the Versions model
* set article.rb to update version.blurb to_eq @article.latest_update when a version is created
**bold**Note: I attempted unsuccessfully to clear the latest_update form in the field also, the same field is present in the new_article view which may not make sense**bold**

More changes:
* Edited History View to use new blurb and also minor cleanup
* Edited mailer to include blurb info
* Added conditional to articles#update to not send email if the latest_update field is blank

Changes to come before merging to production:
* Change Date to EST on history page
* Display environment in update email header
* Add default message to History Page for blank blurbs

**Comment by trystant** [comment] 2015-08-20 23:28
So, here's some feedback:
1. Change Date to EST on history page

You can't change the date to EST because not every user of the site is or will be in EST. I'll need you to review this [article](https://robots.thoughtbot.com/its-about-time-zones) about having timezones per user in our app, which we will need to implement in this app.

**Comment by campgurus** [comment] 2015-08-20 23:29
It's set to local time. Not just est.

**Comment by campgurus** [comment] 2015-08-20 23:29
To clarify. The time zone will match the current user.

**Comment by trystant** [comment] 2015-08-20 23:32
How is that being implemented?

**Comment by campgurus** [comment] 2015-08-20 23:35
I think there is s ruby method called localtime. If you look in
history.html you'll see that is what I am using. Obviously I can only see
one time zone, but we can get some one in a different place to confirm.

**Comment by trystant** [comment] 2015-08-21 01:39
So here is some more feedback:

-  app/assets/javascripts/maps.coffee isn't used, so it needs to be removed, and should not have been added to version control.

- app/assets/stylesheets/maps.scss - also isn't used, so it should be removed

- app/controllers/maps_controller.rb - keeps repeating the same controller code over and over again from line 18 on. Check out `app/controllers/articles_controller.rb` and `app/helper/articles_helper.rb` for the `marker_locations_for` method. This will remove the multiple lines of code that are in `app/controllers/articles_controller.rb` and `app/controllers/maps_controller.rb`

- app/helpers/maps_helper.rb - Remove, since it's not being used

- app/views/maps/index.html.erb - The script at the end of the file should also be put into a helper, since its used in multiple places. This is the one that starts on line 33 with `<script type="">`

- Looking at the history page - The message that is shown when there is no significant change has extra padding on either side caused by the space in the pre tag. The screenshot is shown ![here](http://grandkru.com/images/space_around_text.png)

- If there are no changes, there shouldn't be a sentence that says "Summary of changes in this version" with a box around it. The sentence "There are no significant changes in this version" should replace the sentence and the box.

**Comment by campgurus** [comment] 2015-08-21 17:04
MAde all the above fixes save those related to cleaning up the maps logic. @mark, please take a look when you get  a chance.

**Comment by trystant** [comment] 2015-08-21 17:08
Where should I look at this update? Is it saved to github?

**Comment by trystant** [comment] 2015-08-21 19:17
Based upon this [diff](https://github.com/BOWiki/BOW/compare/3995b3e00daaaf3434a5c49272128e722e50bcea), I have the following comments:

app/controllers/articles_controller.rb:69: `if @article.latest_update != nil && @article.latest_update != ""` can be replaced with `unless @article.latest_update.blank?`

app/mailers/user_notifier.rb: Is there a spec for the different subject lines?

**Comment by campgurus** [comment] 2015-08-22 02:04
I just pushed the blurbs branch adding validation that requires an article to have at least one subject. I added an rspec and factry .  Those specs seem to work fine.  However, after adding the custom validation specs, the geocoder specs are now failing.  full trace:

Failures:

  1) geocoded has a latitude
     Failure/Error: article = FactoryGirl.create(:article)
     ActiveRecord::RecordInvalid:
       Validation failed: An article must have at least one subject
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/validations.rb:79:in `raise_record_invalid'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/validations.rb:43:in `save!'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `block in save!'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `save!'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/models/article_spec.rb:51:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:76:in `block (3 levels) in <top (required)>'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:75:in `block (2 levels) in <top (required)>'

**Comment by trystant** [comment] 2015-08-23 10:46
@campgurus So, the subject validation issue is #87, which is different from this one. I would take the subject validation code out of the 'blurbs' branch and put it into a separate branch off of master, one that starts with '87', such as 87_subject_validation. Put the code in that branch and try running the specs separately.

**Comment by campgurus** [comment] 2015-08-24 21:54
I have managed to make some changes to the factories which seem to have alleviated the validation error.  However, I am now getting a new error.  here is the trace:

1) ArticlesController#create when valid success
     Failure/Error: expect(response).to redirect_to(article_path(Article.last))
     ActionController::UrlGenerationError:
       No route matches {:action=>"show", :controller=>"articles", :id=>nil} missing required keys: [:id]
     # ./.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:259:in `raise_generation_error'
     # ./.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:234:in `optimized_helper'
     # ./.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:220:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:345:in `block (2 levels) in define_url_helper'
     # ./spec/controllers/articles_controller_spec.rb:50:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:76:in `block (3 levels) in <top (required)>'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:75:in `block (2 levels) in <top (required)>'

**Comment by trystant** [comment] 2015-08-26 23:51
What is the actual error that is attached to this stacktrace?

**Comment by campgurus** [comment] 2015-09-14 20:10
the relevant branch is "blurbs"

**Comment by campgurus** [comment] 2015-09-15 16:26
Did we rebase this? I still see some changes on master that are not implemented in the blurbs branch.
<img width="1230" alt="screen shot 2015-09-15 at 12 24 55 pm" src="https://cloud.githubusercontent.com/assets/1260659/9882888/03878d14-5ba5-11e5-815b-22d486d54b0e.png">

**Comment by campgurus** [comment] 2015-09-16 14:09
We are currently adding Cucumber specs as we try to re-add these fixes with more robust testing.

Current failing test has capybara unable to find the form field.  The current field name matches the html id for the element.  here is the error/trace:

```
~/development/blackops$ rake cucumber                                                             *[blurbs] 
/Users/dariusgoore/.rubies/ruby-2.2.1/bin/ruby -S bundle exec cucumber  --profile default
Using the default profile...
Feature: Edit article with blurbs
  In order to send a clear update
  As an editor
  I want to add a summary of my edits

  Scenario: Article Edit With Blurb                                       # features/edit_with_blurbs.feature:6
    Given I am on the show page                                           # features/step_definitions/path_steps.rb:4
    And I follow "Edit"                                                   # features/step_definitions/general_steps.rb:4
    When I fill in "article_latest_update" with "This is my edit summary" # features/step_definitions/general_steps.rb:8
      Unable to find field "article_latest_update" (Capybara::ElementNotFound)
      ./features/step_definitions/general_steps.rb:9:in `/^I fill in "(.*?)" with "(.*?)"$/'
      features/edit_with_blurbs.feature:9:in `When I fill in "article_latest_update" with "This is my edit summary"'
    And I press "Update Article"                                          # features/step_definitions/general_steps.rb:12
    And visit the history page                                            # features/step_definitions/path_steps.rb:10
    Then I should see "This is my edit summary"                           # features/step_definitions/general_steps.rb:16

Failing Scenarios:
cucumber features/edit_with_blurbs.feature:6 # Scenario: Article Edit With Blurb
```

**Comment by trystant** [comment] 2015-09-21 20:47
Taking a look at the state of this branch now. It looks like there is a warning and an error. The error is:
```
 Scenario: Article Edit With Blurb                       # features/Edit_with_blurbs.feature:6
    Given I am on the show page                           # features/step_definitions/path_steps.rb:4
      PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "states_pkey"
      DETAIL:  Key (id)=(33) already exists.
      : INSERT INTO "states" ("name", "id", "ansi_code", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id" (ActiveRecord::RecordNotUnique)
      ./features/step_definitions/path_steps.rb:5:in `/^I am on the show page$/'
      features/Edit_with_blurbs.feature:7:in `Given I am on the show page'
    And I follow "Edit"                                   # features/step_definitions/general_steps.rb:4
    When I fill in "blurb" with "This is my edit summary" # features/step_definitions/general_steps.rb:8
    And I press "Update Article"                          # features/step_definitions/general_steps.rb:12
    And visit the history page                            # features/step_definitions/path_steps.rb:10
    Then I should see "This is my edit summary"           # features/step_definitions/general_steps.rb:16
```
. There is an attached warning which I believe is related

```
[mnyon@mnyon ~/code/ebwiki (git::blurbs) ] rake cucumber
/Users/mnyon/.rvm/rubies/ruby-2.2.1/bin/ruby -S bundle exec cucumber  --profile default
WARNING: You have set Rails' config.cache_classes to false (most likely in config/environments/cucumber.rb).  This setting is known to cause problems with database transactions. Set config.cache_classes to true if you want to use transactions.
```

I think that I need to investigate the state of the DB when tests are running.

**Comment by trystant** [comment] 2015-09-21 21:28
Forensics...

```
[mnyon@mnyon ~/code/ebwiki (git::blurbs) ] rake cucumber
...
[7] pry(#<Cucumber::Rails::World>)> Rails.env
=> "development"
```

```
[mnyon@mnyon ~/code/ebwiki (git::blurbs) ] rake
...
1] pry(#<RSpec::ExampleGroups::Agency>)> Rails.env
=> "test"
```

**Comment by trystant** [comment] 2015-09-21 22:07
For a short term solution, I invoked a `RAILS_ENV= test cucumber`, which runs the features in the test environment. This seems to deal with the failure occurring before. Unfortunately, the test is going to a different page than expected.

While we want to test 
`http://example.com/articles/<article_name>/edit`, 
the feature test looks like the test is not on the Edit Case page as expected, but this page:
`http://www.example.com/guidelines`

We need to put the proper page in.

**Comment by campgurus** [comment] 2016-03-03 18:48
While I am not sure blurbs is the right way to go about adding more descriptive "commit messages" to edits, the need to do better than what we have in place is becoming very clear as we attempt to view changes, made by our first very active public editor.  Viewing the following history tab e.g. :http://ebwiki.org/articles/charly-leundeu-keunang/history it is basically impossible to figure out what changes he has made to the content.

**Comment by campgurus** [comment] 2016-03-22 17:33
I think the solution is to create an associated table commit_messages or something attached to the version s.t. commit_message belongs_to Version.  Trying to figure out hos to create an association with the Versions table which was created within the [paper_trail gem](https://github.com/airblade/paper_trail).

**Comment by campgurus** [comment] 2016-04-06 02:05
I am still trying to figure out the best way to do this.  I was thinking this was like our other nested elements like links, but I am not sure it works.  First of all, once a link is created, that editable link is displayed within the article form. We don't want previous commit messages displayed in the form and nor should they be editable. My current thought is to create a last_version_summary field that saves with the article which will always be on the form displaying the last edit summary.  Then use a callback to edit @article.versions.last.summary, which will be the permanent record of the change summary.

**Comment by campgurus** [comment] 2016-05-15 18:36
We got an answer to this question on SO here: https://stackoverflow.com/questions/36168574/how-to-access-paper-trails-version-model.

The answer points to discussion of "storing metadata" in the paper_trail docs: https://github.com/airblade/paper_trail#4c-storing-metadata

**Comment by campgurus** [comment] 2016-05-17 11:50
With the last commit, this finally works. In all, this is what has been done:
* Added a summary attribute to Article model to store the blurb temporarily
* Added a field for summary within the Article edit/create form
* Add a model method to Article to return the article.summary
* Add a comment attribute to the Versions table to permanently house the summary
* Set meta data to copy the summary into the version comment field
* Set article.summary => nil within the article edit action to make the field blank for editing

Still need to add some rspec to:
* test the validation that editor provides a summary when editing
* test that version has a summary that matches the edit entry 

Non-essential things I would still like to change:
* remove the field for new articles and set the summary field to "article created"
* use a popup form when the user clicks to submit to remind the user to submit a summary of changes

**Comment by campgurus** [comment] 2016-05-17 19:01
helpful tutorial on this is: https://samurails.com/gems/papertrail/

**Comment by campgurus** [comment] 2016-05-18 08:43
One ore thing when this issue is approved.  We should add the summary to the email to followers s.t. they can get a sense of what has been changed in the article without having to visit the site.  At the very least, we need to let them know to check the history tab.

**Comment by trystant** [comment] 2016-05-24 23:48
So I think that the order of the commits should be reversed, most recent first.

I also think that there should be some explanatory text to describe what the history tab does, and to distinguish history of the information written from the history of the case itself. This includes outlining _which_ fields trigger history.

Also, if someone enters the summary without making changes, it just saves without comment. It should raise an error and allow the user to enter/update information

Finally, is there an objection to putting everything in version history? Seems like a lot could slip through the cracks as is...

**Comment by campgurus** [comment] 2016-05-25 08:09
To the last point, ` is there an objection to putting everything in version history?` the answer is no.

If I am understanding correctly, this has already been fixed.  A new version is created when any attribute is changed, with :summary now an exception to that rule.

**Comment by trystant** [comment] 2016-05-25 10:10
but an update doesn't occur if someone updates any associated pieces, such as subjects, links or comments.

**Comment by campgurus** [comment] 2016-05-25 10:15
Not at this time.  Let's release this and make a new issue for associated objects. Actually, the issue already exists  in #481.

**Comment by trystant** [comment] 2016-05-25 10:17
Then that needs to be added to the copy on the history page, otherwise it's not really clear.

**Comment by campgurus** [comment] 2016-05-25 10:21
Ok.  But rather than me interpreting what you are saying, making changes, coming back to you, making more changes, can you just edit the following text which is currently there to change it to what you want?

> Any time any information about a case is updated, a new version is created. This page shows the history of this article and lists all the changes that have been made to the article over time.

**Closed** 2016-05-30 23:44 UTC
Labels: alpha release, P2
